### PR TITLE
Fix error message for invalid prefixes in edit command arguments

### PR DESCRIPTION
**Pull request by cjyothika**
Fix issues #159 , #147 , #150.
- Parse prefixes before parsing module code to detect invalid prefixes correctly.
- Change error message for missing valid prefixes to invalid command format error message.

### CODE REVIEW

**Review by Jun-How — COMMENTED** [review]
I was thinking that instead of replacing the `MESSAGE_NOT_EDITED`, we could add a check at the start for the case when no prefix is present and the preamble either contains a whitespace or a special character, and then continue parsing the code as per normal.

I have tried implementing it in code like this:
```
public static Pattern pattern = Pattern.compile("^[a-zA-Z0-9]+$");
...
boolean isAnyPrefixPresent = isAnyPrefixPresent(argMultimap, PREFIX_CODE, PREFIX_CREDIT, PREFIX_SEMYEAR, PREFIX_GRADE, PREFIX_TAG);
boolean containsNonAlphanumeric = !pattern.matcher(preamble).find();
if (preamble.isEmpty() || (!isAnyPrefixPresent && (preamble.contains(" ") || containsNonAlphanumeric))) {
     throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, EditCommand.MESSAGE_USAGE));
}
```
```
/**
     * Returns true if at least one of the prefixes contains non-empty {@code Optional} values in the given
     * {@code ArgumentMultimap}.
     */
    private static boolean isAnyPrefixPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
        return Stream.of(prefixes).anyMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
    }
```

The rationale is that it covers more specific cases like if a correct module code is given without any prefixes , shown in this screenshot below:
image

**Comment by cjyothika** [comment]
@Jun-How I think message_not_edited is not very useful tbh but you can put up your changes in a separate PR. I'll try to test it from there.

**Comment by Jun-How** [comment]
I guess this can be merged if everyone else is good with it.

**Comment by Jun-How** [comment]
Merging this.

**Pull request merged**
