### PR TITLE
Sort command

### PR DESCRIPTION
**Pull request by cjyothika**
Used a public enum in SortCommand to tell Ui what sort it is. Idk if that's violating OOP

Edit: Nevermind, I changed this because I think it increases coupling

### CODE REVIEW

**Comment by jmestxr** [comment]
@cjyothika alright can merge alr once u done

**Comment by jmestxr** [comment]
@cjyothika are you able to save the previous sort state somewhere in Model? like how currently the find command alters the list of filtered modules in Model "permanently". So that I can implement the case whereby: the user presses other tabs and then presses on the `Module List` tab again, the modules will not be resorted back to default (by year).

**Comment by cjyothika** [comment]
> @cjyothika are you able to save the previous sort state somewhere in Model? like how currently the find command alters the list of filtered modules in Model "permanently". So that I can implement the case whereby: the user presses other tabs and then presses on the `Module List` tab again, the modules will not be resorted back to default (by year).

@jmestxr I stored the previous sort in UniqueModelList. There is a method in logic and model to retrieve the previous/current sort called getSort().

**Comment by cjyothika** [comment]
@jmestxr I changed the handler so that it does not go back to default after going to a different section.

**Review by jmestxr — APPROVED** [review]

**Pull request merged**
