### PR TITLE
Update AboutUs (James), PPP (James), README, UG

### PR DESCRIPTION
**Pull request by jmestxr**

### CODE REVIEW

**Review by Dangabit — COMMENTED** [review]
In UG, the tutor said something about including just a plain list of commands for easier referencing. Should we include that somewhere?

Also try to fix the checks so we won't have any problems about this next time.

**Comment by Jun-How** [comment]
> Okay, I'll include that in a while.
> 
> BTW, how to fix those checks?

Need to resolve the errors as shown under "Details":

image

**Comment by jmestxr** [comment]
I have just included a Command Summary section in the UG. Just a few suggestions when I was doing the UG:
- we could change the name of the command `list` (for listing modules) into something more general `show`, which can include specific arguments like `show modules`, `show progress`, `show modules /y y1s1`, etc. When executed, `show` command will display results on the graphical section (left section) of our GUI.
- Instead of `clear` (which deletes all modules), we could move it to the `delete` command, specifying it as `delete all` which deletes all modules. (I think we talked about this the previous meeting but forgot why we didn't agree to this..)

**Comment by Dangabit** [comment]
For the `list` into `show`, I think possible, but if the command modifies different parts of the app (eg. the stats part and the "terminal" part), not sure if same command would be a good idea.

For the clear part, I think the idea is that we will do in the next few iterations when we overhaul some parts of the commands. So for the iteration (v1.2), we try to modify our data (models, logic, whatever) from Address to Module first.

**Review by Dangabit — APPROVED** [review]
lgtm xd

**Pull request merged**
