### PR TITLE
Fix negative degree progression

### LINKED ISSUE #153: [PE-D][Tester B] Degree Progress in Negative
I created 2 test modules as shown below: 

Since the module with 99 MCs were not rejected, I assumed that it was a potential valid module. However on the progress screen, the module progress has become negative: 

I have marked this as low severity as this is a very unlikely scenario where a mod is worth 99 MCs however this could be a potential bug in the way MCs are calculated.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: dillongoh/ped#5

### PR DESCRIPTION
**Pull request by Dangabit**
Fix #153 : Computing degree progress has now changed to deal with duplicated credits causing an issue. I have not tested on >2 tags, or duplicate tags with UE, or different ordering of multi tags modules...

The change:
Split modlist into single tag and multi tag.
Insert all single tags first.
For each multitag, check how much to duplicate, then insert into the requirements.
How much to duplicate is calculated by $\Sigma(min(credit, remaining\, capacity)) - credit$, limited to be non-negative.

Honestly, I forsee the ordering of multi tagged modules being somewhat an issue.

### CODE REVIEW

**Comment by Dangabit** [comment]
Yepp ordering of module is an issue, this doesn't work fully yet.

**Comment by Dangabit** [comment]
New fix: Allow for negative duplication credit to remove ordering issue. Also added error handling for total duped credit < 0 by telling the user that their list of modules is most likely invalid based on how they tagged them.

I also think we should probably have tightened the range available for the user's inputs to credit and tags, but then that's probably a feature flaw...

**Comment by Dangabit** [comment]
@AY2223S2-CS2103T-T13-1/developers please help to run some random "valid" list of modules to make sure the error doesn't show up for actual valid list of modules once merged.

**Comment by Jun-How** [comment]
Oh ya, possible to also change to disallow "F" grade module from being counted to MCs completion?

**Comment by Dangabit** [comment]
> Oh ya, possible to also change to disallow "F" grade module from being counted to MCs completion?

Oright I missed that out, done.

**Pull request merged**
